// Builds src/sje/interfaces.check.ts from the code blocks of docs/engine/interfaces.md, so the design sketches are compiled
// under the repo's strict settings and a drift between the doc and the compiler's idea of the types is a compile error
// (or a failing test: tests/sje-interfaces.test.ts compares the file with what this builds).
//
//   node scripts/sync-interface-check.mjs        rewrite the file
//
// The sketches are written as `export class X { method(): T; }` and `export const x: T;`, which only compile in an ambient
// context. So each block is copied with `declare` added in front of every top-level class and const, and nothing else changes.
// Three value lines of block 1 (`W`, `H`, `FPS`, `TICK_MS`, `grain`) have initializers, which an ambient file cannot hold; they are
// replaced by their types, listed in VALUE_LINES. A new value line in the doc stops the build until it is listed here.
//
// The names that the doc says are not part of the design (`Ctx`, `SceneDump`, `EmitterPreset`...) come from the stubs at the top.

/** The value-level lines of the sketches, and the declaration that stands for each in the ambient file. */
export const VALUE_LINES = new Map([
  ['export const W = 640, H = 360, FPS = 60;', 'export declare const W: 640, H: 360, FPS: 60;'],
  ['export const TICK_MS = 1000 / FPS;', 'export declare const TICK_MS: number;'],
  ['export const grain = (n: 1 | 2 | 4) => ({ w: W / n, h: H / n });', 'export declare const grain: (n: 1 | 2 | 4) => { w: number; h: number };'],
]);

export const STUBS = `import type { DisplayHost } from './display/gameobject';

// ---- stubs: names the sketches use and the doc says are not part of the design (interfaces.md, "Types that are not shown") ----
type Ctx = CanvasRenderingContext2D; // today's canvas context (src/engine/canvas.ts)
type Fighter = Record<string, unknown>;
type StageData = Record<string, unknown>;
type HackDef = Record<string, unknown>;
type SceneDump = Record<string, unknown>; // the JSON tree of the DEV hook
type EmitterPreset = Record<string, unknown>;
type InputDevice = 'keyboard' | 'gamepad' | 'touch';
/** Today's \`Scene\` shape, wrapped by the \`LegacyScene\` adapter (M1). */
interface LegacyScene<R = unknown> {
  opaque: boolean;
  curtain: boolean;
  passUpdate: boolean;
  update(): void;
  render(ctx: Ctx): void;
  close(result: R): void;
}
// Used by sketches that only name them in comments or signatures.
export type { Ctx, DisplayHost, EmitterPreset, Fighter, HackDef, InputDevice, LegacyScene, SceneDump, StageData };
`;

/** The \`ts\` code blocks of the doc, in order. */
export function blocksOf(md) {
  const blocks = [];
  for (const m of md.matchAll(/```ts\n([\s\S]*?)```/g)) blocks.push(m[1]);
  return blocks;
}

/** One block, made ambient. */
export function ambient(block, index) {
  let out = block;
  for (const [from, to] of VALUE_LINES) out = out.replace(from, to);
  out = out.replace(/^export (abstract )?class /gm, 'export declare $1class ').replace(/^export const (\w+): /gm, 'export declare const $1: ');
  const left = out.match(/^export const \w+\s*=/gm);
  if (left) throw new Error(`interfaces.md block ${index + 1} has a value line with an initializer that scripts/lib/interface-check.mjs does not know: ${left.join(', ')}`);
  return out;
}

/** The whole file. */
export function buildCheckFile(md) {
  const header = `/**
 * GENERATED by scripts/sync-interface-check.mjs from the code blocks of docs/engine/interfaces.md (M0). Do not edit by hand:
 * change the doc and run the script. tests/sje-interfaces.test.ts fails when the two disagree.
 *
 * Types only, no runtime: nothing imports this file, so it is not in any bundle. \`npm run typecheck\` compiles it under the
 * repo's strict settings (\`exactOptionalPropertyTypes\` and \`noUncheckedIndexedAccess\` included). A sketch that does not compile
 * is a design error to fix in the doc, or a real conflict between two interfaces.
 */
`;
  const blocks = blocksOf(md).map((b, i) => `// ---- interfaces.md block ${i + 1} ----\n${ambient(b, i)}`);
  return `${header}${STUBS}\n${blocks.join('\n')}`;
}
